## DB config
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.29.115:3306/test
      username: root
      password: sl250611
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
  thymeleaf:
    prefix: classpath:/thymeleaf/
    suffix: .html

## redis config
#  redis:
#    host: localhost
#    port: 6379

## kafka config
#  kafka:
#    bootstrap-servers: localhost:9092

## mybatis config
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.athena.px.model



