athena:
  host: 47.96.81.112
  chat-server: 172.16.23.147

## DB config
spring:
  resources:
    static-locations: classpath:/resources/,classpath:/webapp/
  thymeleaf:
    prefix: classpath:/thymeleaf
    suffix: .html

## redis config
#  redis:
#    host: localhost
#    port: 6379

## kafka config
  kafka:
    producer:
      bootstrap-servers: ${athena.host}:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      batch-size: 100
      client-id: spring-boot-demo

server:
  port: 8080

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

jwt:
  header: ACCESS_TOKEN
  expire: 1800






