
## DB config
spring:
  thymeleaf:
    prefix: classpath:/thymeleaf/
    suffix: .html

## redis config
#  redis:
#    host: localhost
#    port: 6379

## kafka config
  kafka:
    bootstrap-servers: 192.168.2.129:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 1



server:
  port: 8080





